local: &local
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: wonder
  password:
  #min_messages: warning

# Local database
development:
  <<: *local
  database: wonderbars_development

test:
  <<: *local
  database: wonderbars_test

production:
  <<: *local
  database: wonderbars_production

# Heroku
stage:
  adapter: postgresql
  encoding: unicode
  host:
  port:
  database:
  pool:
  username:
  password:


